name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
      
    - name: Build and Test
      run: xcodebuild test -project Wardrobe.xcodeproj -scheme Wardrobe -destination 'platform=macOS' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
